//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Access_Level
    {
        public int Access_Level_Id { get; set; }
        public string Access_Level_Name { get; set; }
        public string Access_Level_Description { get; set; }
    }
}
