//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Unit_Price_Log
    {
        public int Order_Price_Log_ID { get; set; }
        public Nullable<int> Order_Price_ID { get; set; }
        public Nullable<decimal> Order_Price { get; set; }
        public Nullable<System.DateTime> Order_Price_Year { get; set; }
    
        public virtual Order_Unit_Price Order_Unit_Price { get; set; }
    }
}
