//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales_Unit_Price_log
    {
        public int Sales_Price_Log_ID { get; set; }
        public Nullable<decimal> Sales_Price { get; set; }
        public Nullable<System.DateTime> Sales_Price_Year { get; set; }
        public Nullable<int> Sales_Price_ID { get; set; }
    
        public virtual Sales_Unit_Price Sales_Unit_Price { get; set; }
    }
}
